[env]
TERM = "tmux-256color"
[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session","-A","-s","main"]

[colors.primary]
background = "#181f21"  # Matches the GTK dark theme background
foreground = "#dadada"  # Matches the text color in gtk-dark.css
dim_foreground = "#afb4ba"
bright_foreground = "#dadada"

[colors.cursor]
text = "#181f21"
cursor = "#6695a3"  # Cursor color from the selected elements in GTK

[colors.vi_mode_cursor]
text = "#181f21"
cursor = "#6695a3"

[colors.search.matches]
foreground = "#181f21"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#181f21"
background = "#6695a3"

[colors.footer_bar]
foreground = "#181f21"
background = "#a6adc8"

[colors.hints.start]
foreground = "#181f21"
background = "#f9e2af"

[colors.hints.end]
foreground = "#181f21"
background = "#a6adc8"

[colors.selection]
text = "#181f21"
background = "#6695a3"  # Matches GTK selection color

[colors.normal]
black = "#45475a"
red = "#ae5058"  # From GTK button links
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#6695a3"  # Matched with GTK blue selection color
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#db5b5b"  # More vibrant red from GTK buttons
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#6695a3"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#6695a3"  # GTK blue accent

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"
opacity = 0.85  # Transparency (Requires Picom)
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[scrolling]
history = 10000
multiplier = 3

#[[keyboard.bindings]]
#key = "B"
#mods = "Control|Shift"
#action = "None"

[keyboard]
bindings = [] # Completely disable all alacritty keybinding :D

[terminal]
